### ISSUE TITLE
barn2-plugins-header-heading font-size should be set to 14px

### ISSUE THREAD

**Issue by alessandrotesoro** [Barn2Media/easy-post-types-fields#1]
Hi @LuigiPulcini 

Sorry for opening an issue on here. I'm going through the initial feedback I've received from Katie in regards to the table generator that will be introduced in some of our plugins soon and we're making sure that things are consistent. Even tiny details such as this.

Could you please change the font-size of the `h1` tag with class `.barn2-plugins-header-heading` from `16px` to `14px`.

Let me know if you wish me to open a PR and I can do it 👍 

Thank you.

**Comment by LuigiPulcini** [comment]
No worries, Alessandro. I can do that without any problem. 👍
I need to release a new version as soon as DLP and WPT add a call to `shortcode_atts`. So, this change will be deferred to that version.

**Comment by LuigiPulcini** [comment]
This was resolved in version 1.1.0
