### ISSUE TITLE
Possible bug with PTP integration

### ISSUE THREAD

**Issue by andykeith** [Barn2Media/easy-post-types-fields#2]
Hi Luigi,

During a recent PTP test, one of my test tables threw an exception in EPT.

My posts table shortcode is (showing normal Posts): 
[posts_table columns="title,cf:post_date" filters="categories,tags"]

My custom field is a regular WP custom field, not an ACF field. For some posts in my table, there are 2 or more fields with the same field key, e.g.

<img width="920" alt="Screenshot 2022-08-24 at 20 16 09" src="https://user-images.githubusercontent.com/4103194/186493769-d57cab7f-f25a-4609-9128-a680cb0574dc.png">

Here's the error trace:

<img width="672" alt="Screenshot 2022-08-24 at 20 16 22" src="https://user-images.githubusercontent.com/4103194/186493934-0cb7d5c1-75eb-41d6-a7f8-439694d1c4d9.png">

Let me know if you need any more info to debug this.

**Comment by LuigiPulcini** [comment]
Hi, Andy,

Thanks for pointing that out.

I stumbled upon similar fatal errors and am assuming you are testing in PHP 8.0+. The array_ functions used to throw a warning in PHP 7.4 but throw fatal errors in PHP 8.0.

I will add the necessary safeguard to prevent all this from happening. In this specific case, it would be enough to type-cast the result of `get_post_meta` into an array in the following line:

https://github.com/Barn2Media/easy-post-types-fields/blob/f0f6e13cb85ce679585f948936417f8f21b1d15f/src/Integration/Barn2_Table_Plugin.php#L192

I will fix this tomorrow and release an update right away.

**Comment by andykeith** [comment]
Hi Luigi,

Thanks, that sounds good. Yes I'm running locally with PHP 8.0. 

Out of interest, what changed exactly with the array functions in 8.0? I'd be interested to know as I wasn't aware of this.

**Comment by LuigiPulcini** [comment]
[This is an article](https://php.watch/versions/8.0/internal-function-exceptions) detailing the change, the scope of which is broader than what I previously mentioned, since it applies to any function that expects a parameter of a specific type. In PHP 7.4, a warning would be triggered. Starting from PHP 8.0, a TypeError is thrown.

**Comment by LuigiPulcini** [comment]
This problem was resolved in version 1.1.1, released on 29 August 2022
