### ISSUE TITLE
Missing "Edit [post type]" link in admin bar

### ISSUE THREAD

**Issue by andykeith** [Barn2Media/easy-post-types-fields#3]
Post types created in EPT don't have an Edit link in the admin bar.

Steps to reproduce:
- Create a post type, then publish a post for that post type.
- View the post on the front end while logged in.
- In the admin bar the 'Edit ... ' link is missing.

For other post types (e.g. posts, pages, CPTs created in other plugins) you have the 'Edit' link. For example, this is the admin bar for a 'Book' post created in Pods:

<img width="302" alt="Screenshot 2022-09-29 at 12 53 52" src="https://user-images.githubusercontent.com/4103194/193013900-f5dde373-5231-4f27-b165-ccd5bab6a099.png">

**Comment by amirition** [comment]
Fixed in version 1.1.2
