### ISSUE TITLE
Setup wizard opens on subsequent activations

### ISSUE THREAD

**Issue by Barn2** [Barn2Media/easy-post-types-fields#6]
The setup wizard is only supposed to auto-launch the first time a plugin is activated, but the Easy Post Types wizard launches every time. Please could you change this.

**Comment by amirition** [comment]
@Barn2 I already resolved this issue here: https://github.com/Barn2Media/easy-post-types-fields/issues/4 

It doesn't happen after version 1.1.2. 

Could you please check on the latest version and let me know?
