### ISSUE TITLE
Notice: Function register_uninstall_hook was called incorrectly

### ISSUE THREAD

**Issue by alessandrotesoro** [Barn2Media/easy-post-types-fields#7]
Hey @amirition 

The plugin is firing this message at all times. At the moment we do not use the deactivation hook so please remove 

```
register_uninstall_hook( $this->file, [$this, 'on_uninstall'] ); 
```

In file `src/Admin/Plugin_Setup.php` in the next update.

Thank you 👍

**Comment by amirition** [comment]
I was using that hook to determine if I should run the setup wizard or not, not it's running properly in version 1.1.4.
