### ISSUE TITLE
Can't delete custom field value

### ISSUE THREAD

**Issue by FaycalBoutam** [Barn2Media/easy-post-types-fields#8]
> **Summary**
> Easy Post Types and Fields > Custom Field value cannot be deleted
> 
> **Steps to replicate**
> I have a custom post type called Articles.
> Visit this link to edit the custom post: https://adrian.wppluginsupport.net/wp-admin/post.php?post=1004&action=edit
> Try removing the value of the "My Custom Field" field, save, refresh the page, and you'll see that the value is not deleted.
>
> **Outcome**
> I cannot delete the value of the custom field I created.
> 
> **Expected Outcome**
> I should be able to delete the value of the custom field I created.

It happens in [this line](https://github.com/Barn2Media/easy-post-types-fields/blob/master/src/Post_Types/Abstract_Post_Type.php#L270), removing that second check fixes the issue.

Ticket: https://secure.helpscout.net/conversation/2347577064/92004?folderId=7603842

**Comment by LuigiPulcini** [comment]
Instead of removing the second condition, I would suggest to transform the `if` clause as follows:

```php
if ( isset( $postdata[ $meta_key ] ) && '' !== $postdata[ $meta_key ] ) {
    update_post_meta( $post_id, $meta_key, $postdata[ $meta_key ] );
} else {
    delete_post_meta( $post_id, $meta_key );
}
```

This way we don't litter the database with unnecessary metadata.

**Comment by amirition** [comment]
Thanks @FaycalBoutam and @LuigiPulcini. I have fixed this in the new release of the plugin.
